# **머신러닝 모델 템플릿**

<br>

### **TIPS 데이터 활용하여 쉽게 모델링하기**
- 간단하게 쉽게 머신러닝 모델링 만들어 보기
- 원하는 컬럼을 선택해서 회귀 모델, 분류 모델 만들어 보기
- 잘 몰라도 아래 순서에 맞게 , 이런식으로 실행하면 되겠구나 느끼기
- 여러분이 처음 한다고 생각하고 템플릿 작성함

### **모델링 프로세스**
1. 데이터 가져오기
2. 데이터 분석
3. X , y 나누기
4. 머신러닝 모델링

<br>

## **0. tips2.csv 데이터 만들기**

In [ ]:
!pip install seaborn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


tips = sns.load_dataset('tips')

tips.sex.replace(['Female', 'Male'], [0,1], inplace=True)
tips.smoker.replace(['No', 'Yes'], [0,1], inplace=True)
tips.time.replace(['Dinner', 'Lunch'], [1,0], inplace=True)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
tips.day = le.fit_transform(tips.day)

tips.to_csv('tips2.csv', index=False)

<br>
<br>
<br>

---

## **1. 데이터 가져오기**
- 먼저, 데이터가 있어야 모델링을 만들수 있다.
- 데이터 가져오는 방법에는 여러가지 있다.
 - 본인 데이터를 직접 올리는 방법
 - 기존에 제공하는 데이터 가져다 쓰는 방법
- 반드시 데이터를 읽어와야 후속 작업을 할수 있다.

In [ ]:
# 필요한 라이브러리 가져오기
# 그냥 무조건 가져온다고 생각하자 : pandas, numpy, seaborn, matplotlib.pyplot
# seaborn 설치가 되어 있지 않으면 라이브러리는 설치 필요 : !pip install seaborn
!pip install seaborn

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Requirement already satisfied: seaborn in c:\users\user\anaconda3\lib\site-packages (0.11.2)
Requirement already satisfied: numpy>=1.15 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (1.21.5)
Requirement already satisfied: pandas>=0.23 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (1.4.4)
Requirement already satisfied: matplotlib>=2.2 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (3.5.2)
Requirement already satisfied: scipy>=1.0 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (1.9.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (9.2.0)
Requirement already satisfied: packaging>=20.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (1.4.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (4.25.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas>=0.23->seaborn) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.2->seaborn) (1.16.0)

In [ ]:
# 우리는 직접 데이터를 가지고 실습을 진행한다.
# 파일명 : tips2.csv
# 판다스에서 csv 파일을 읽는 함수는 뭘까? 외우면 좋다. 못외웠다면?
# 먼저, 판다스에 있는 함수를 찾는다.  그냥 외워라!!

dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '_typing',
 '_version',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [ ]:
#  판다스의 read_csv 함수를 찾았는데, 사용법을 모른다면
# 1. 아래와 같이 help 찾는다. ? , shift+Tab 2가지 방법으로 쥬피터 노트북에서 help을 볼수 있다.
# 2. 구글링 : pandas read_csv --> 판다스 사이트 접속해서 도움말 보기 : https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

pd.read_csv?

In [ ]:
# 글 완성 기능 활용 : 함수명 쓰다가 Tab 키를 누르면 관련된 함수명들 나열됨
# read 뒤에 커서 위치하고 Tab키 누르기

pd.read

In [ ]:
# tips2.csv 파일을 판다스의 read_csv() 함수를 활용해서 읽기
# 화면에 보이는 엑셀처럼 보이는 테이블은 데이터프레임이다.

pd.read_csv('tips2.csv')

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     1     2
1         10.34  1.66    1       0    2     1     3
2         21.01  3.50    1       0    2     1     3
3         23.68  3.31    1       0    2     1     2
4         24.59  3.61    0       0    2     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

[244 rows x 7 columns]

### TIPS 데이터셋 가져오기

In [ ]:
# tips2.csv 파일 읽고  tips2 데이터프레임에 저장합니다.

tips2 = pd.read_csv('tips2.csv')

In [ ]:
# head() 함수를 통해서 tips2 데이터프레임의 앞 5개 데이터를 확인 할수 있으며
# 인덱스와 컬럼들과 value값들로 구성됩니다.

tips2.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     1     2
1       10.34  1.66    1       0    2     1     3
2       21.01  3.50    1       0    2     1     3
3       23.68  3.31    1       0    2     1     2
4       24.59  3.61    0       0    2     1     4

![tips](https://github.com/gzone1357/Image1/raw/main/git1.png)

### 주어진 데이터프레임(테이블)에서 행과 열 접근해 값 가져오기

In [ ]:
# tips2 데이터프레임(테이블) 내용 다시 확인해 봅시다.

tips2

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     1     2
1         10.34  1.66    1       0    2     1     3
2         21.01  3.50    1       0    2     1     3
3         23.68  3.31    1       0    2     1     2
4         24.59  3.61    0       0    2     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

[244 rows x 7 columns]

### tip 컬럼의 내용만 가져와 보기

In [ ]:
# 'tip' 1개의 컬럼만 가져올 경우 , 아래 화면 출력처럼 인덱스와 value값으로 구성되며
# 이런 형태를 시리즈라고 합니다.

tips2[ 'tip' ]

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

### tip, day, size 3개의 컬럼 내용 가져와 보기

In [ ]:
# 리스트[]를 사용하여 tip, day, size 3개의 컬럼 이름을 담아
# 지정된 tip, day, size  3개의 컬럼에 대해서만 데이터를 가져옵니다.

col = [ 'tip', 'day', 'size' ]
tips2[ col ]

      tip  day  size
0    1.01    2     2
1    1.66    2     3
2    3.50    2     3
3    3.31    2     2
4    3.61    2     4
..    ...  ...   ...
239  5.92    1     3
240  2.00    1     2
241  2.00    1     2
242  1.75    1     2
243  3.00    3     2

[244 rows x 3 columns]

In [ ]:
# 위에서 실행한 코드와 똑같은 결과를 만드는 코딩입니다.

tips2[ [ 'tip', 'day', 'size' ] ]

      tip  day  size
0    1.01    2     2
1    1.66    2     3
2    3.50    2     3
3    3.31    2     2
4    3.61    2     4
..    ...  ...   ...
239  5.92    1     3
240  2.00    1     2
241  2.00    1     2
242  1.75    1     2
243  3.00    3     2

[244 rows x 3 columns]

### 이번에 첫번째 행을 접근해 보자

In [ ]:
# 다시 tips 데이터프레임(테이블) 내용을 살펴 보자
# 첫번째 행의 내용도 확인해 보자

tips2

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     1     2
1         10.34  1.66    1       0    2     1     3
2         21.01  3.50    1       0    2     1     3
3         23.68  3.31    1       0    2     1     2
4         24.59  3.61    0       0    2     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

[244 rows x 7 columns]

In [ ]:
# 첫번째 행(0번 라인)을 접근하기 위해 아래와 같이 0 입력 했으나 에러가 발생
# 데이터프레임에 1개의 요소를 넣으면 무조건 컬럼으로 인식하게 되어 0 이라는 컬럼을 찾게 되지만,
# 0 이라는 컬럼이 없어 에러가 발생하게 됩니다.

tips2[ 0 ]

KeyError: 0

In [ ]:
# tips2 데이터프레임(테이블)에서 행들을 접근하기 위해서는 슬라이싱 필요
# 슬라이싱(0 : 1) 사용해서 첫번째 행(0번 라인)을 접근

tips2[ 0 : 1 ]

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     1     2

### 5번째부터 9번째 행들을 출력해 보자

In [ ]:
# tips2 데이터프레임(테이블)에서 행들을 접근하기 위해서는 슬라이싱 필요
# 슬라이싱(5 : 10) 사용해서 인덱스 5번부터 9번까지의 행 라인을 접근

tips2[ 5 : 10 ]

   total_bill   tip  sex  smoker  day  time  size
5       25.29  4.71    1       0    2     1     4
6        8.77  2.00    1       0    2     1     2
7       26.88  3.12    1       0    2     1     4
8       15.04  1.96    1       0    2     1     2
9       14.78  3.23    1       0    2     1     2

<br>
<br>
<br>

---

## **2. 데이터 분석**
- 데이터 값이 어떻게 되어 있으며, 어떤 흐름을 보이는지, 다른 컬럼과의 관계는 어떤지를 파악하는 거다.
- 눈으로 데이터 수치를 보고 어떤 흐름인지 파악할수 있지만,
- 시각화를 통한다면 쉽게 흐름을 파악할수 있으니, 할수 있으면 사용해라.
- 여러분에게는 어려울수 있으니, 아, 이렇게 데이터를 가지고 시각화를 할수 있구나 느낀면 된다.

### **<font color=blue>하지만, 우리는 여기서는 데이터 분석을 하지 않아요.</font>**
### **<font color=red>데이터가 이미 정제되어 있어 머신러닝과 딥러닝 모델링에 집중하도록 할게요!!</font>**

<br>
<br>
<br>

---

## **3. [회귀모델 ] X, y 나누기**
- 지도학습 경우 데이터와 정답이 있어야 합니다.
- 데이터에 해당하는 X와 정답에 해당하는 y가 있어야 합니다.
- 아래와 같이 판다스를 이용하면 X, y를 쉽게 나눌수 있어요.
- X, y 데이터를 가지고 모델 학습하고 검증할수 있는 학습 데이터셋과 테스트 데이터셋으로 나눠 사용합니다.
- 그리고 레이블(y) 값을 보고 회귀 모델인지, 분류 모델인지 구별할수 있어요
  - 레이블(y) : 학점 A/B/C/DF , 남녀 남/여, 숫자 0~9 --> 범주형으로 되어 있으면 분류 모델
  - 레이블(y) : 삼성전자 주가, 습도/온도, 유가동향등 --> 연속형으로 되어 있으면 회귀 모델

### **<font color=blue>우리는 회귀 모델을 만들어야 하는데, 어떤 컬럼을 정답(레이블, y)를 정할까요?</font>**
### **<font color=blue>회귀모델 위해서 연속형 컬럼을 레이블(y)로 선택해야 합니다.</font>**

In [ ]:
# tips2 데이터프레임의 뒤 5개 행 라인 보기
# 연속적인 값들이 있는 컬럼은 무엇이 있나요?

tips2.tail()

     total_bill   tip  sex  smoker  day  time  size
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

### **<font color=blue>연속적인 값을 나타내는 컬럼이 total_bill, tip 컬럼들이 있네요</font>**

In [ ]:
# 다시 한번 tips2 내용을 보겠습니다.

tips2.head(3)

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     1     2
1       10.34  1.66    1       0    2     1     3
2       21.01  3.50    1       0    2     1     3

### **그중에서 정답(레이블, y)을 tip 컬럼으로 정했고, tip의 값들이 연속적인 값이니 <font color=blue>회귀 모델</font>이 되겠네요.**

In [ ]:
# tips2 데이터프레임(테이블)에서 tip 컬럼만 제외하면 나머지가 X가 되겠네요.
# tips 컬럼을 제외하고 나머지 컬럼들을 일일히 리스트에 나열해 조회해 보겠습니다.

tips2[['total_bill', 'sex', 'smoker', 'day', 'time', 'size']]

     total_bill  sex  smoker  day  time  size
0         16.99    0       0    2     1     2
1         10.34    1       0    2     1     3
2         21.01    1       0    2     1     3
3         23.68    1       0    2     1     2
4         24.59    0       0    2     1     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       0    1     1     3
240       27.18    0       1    1     1     2
241       22.67    1       1    1     1     2
242       17.82    1       0    1     1     2
243       18.78    0       0    3     1     2

[244 rows x 6 columns]

In [ ]:
# 레이블(y)는 tips2 데이터프레임(테이블)에서 tip 컬럼만 가져오면 되겠네요.
# 출력 결과는 인덱스와 value값으로 이루어진 시리즈 형태입니다.

tips2['tip']

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

### **<font color=blue>판다스의 drop 함수를 이용하면 쉽게 X, y를 나눌수 있어요!!</font>**

In [ ]:
# ? 활용하여 도움말 보기
tips2.drop?

In [ ]:
# Tab 키를 이용해서 자동 완성 황용하기
tips2.dro

In [ ]:
# X 데이터 분리 : 판다스 drop 함수 활용
# 입력 : 'tip', axis=1

X = tips2.drop('tip', axis=1)

In [ ]:
# 분리된 X 데이터 확인 : 데이터 타입이 데이터프레임 확인
# 레이블 tip 컬럼은 보이지 않음을 확인할수 있습니다.

X

     total_bill  sex  smoker  day  time  size
0         16.99    0       0    2     1     2
1         10.34    1       0    2     1     3
2         21.01    1       0    2     1     3
3         23.68    1       0    2     1     2
4         24.59    0       0    2     1     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       0    1     1     3
240       27.18    0       1    1     1     2
241       22.67    1       1    1     1     2
242       17.82    1       0    1     1     2
243       18.78    0       0    3     1     2

[244 rows x 6 columns]

In [ ]:
# y 데이터 분리 : 'tip' 컬럼값만 분리해서 가져오면 됨.

y = tips2['tip']

In [ ]:
# 분리된 y 데이터 확인 : 데이터 타입이 Series 확인
# y 값이 실수형으로 되어 있음 확인

y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

### **X, y 데이터를 가지고 학습 데이터셋과 테스트 데이터셋 만들어 볼게요.**

In [ ]:
# X, y 데이터를 가지고 학습 데이터셋과 테스트 데이터셋 만들어 주는 train_test_split 함수가 있습니다.
# train_test_split 함수를 이용하면 쉽게 학습 데이터셋과 테스트 데이터셋 만들수 있습니다.
# 사이킷런의 train_test_split 함수 불러 옵니다.

from sklearn.model_selection import train_test_split

In [ ]:
# ? 활용하여 도움말 보기
train_test_split?

In [ ]:
# train_test_split 함수
# 1. X ,y 입력
# 2. test_size=0.2 --> train set : test set  = 8 : 2
# 3. random_state 사용하지 않으면 실행할때마다 학습셋과 테스트셋이 다르게 나와 고정하기 위해 사용
# 4. train_test_split 함수 결과로 X_train, X_test, y_train, y_test 나옴.

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42 )

In [ ]:
# 학습 데이터셋과 테스트 데이터셋의 사이즈 확인

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((195, 6), (49, 6), (195,), (49,))

In [ ]:
# 뒤쪽에서 사용하게 편하게 데이터프레임을 넘파이(numpy)로 변경합니다.

X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values

<br>
<br>
<br>

---

# **머신러닝 모델 포맷**

![머신러닝 포맷](https://github.com/gzone1357/Image1/raw/main/git2.png)

<br>
<br>
<br>

---

## **4. (회귀) 머신러닝 모델링**
- DecisionTree 결정트리
- RandomForest 앙상블

### DecisionTree

![결정트리](https://github.com/gzone1357/Image1/raw/main/tree-depth-2.png)

In [ ]:
# 외우면 좋지만, 다 외울수 없기에
# Tab 키를 활용해서 자동완성 사용하자.
# 그리고 레이블(y)값을 tips로 정햇으니, 연속적인 값들이므로 회귀 모델입니다.
# 회귀 모델을 선택해야 합니다.

from sklearn.tree import De

In [ ]:
# DecisionTree 머신러닝 모델링

from sklearn.tree import DecisionTreeRegressor

In [ ]:
# ? , shift+Tab 활용하여 도움말 보기
DecisionTreeRegressor?

In [ ]:
# 1. DecisionTreeRegressor 모델 정의 -> dtr 저장
# 2. dtr 모델 학습 : X_train, y_train
# 3. dtr 모델 성능확인 : X_test, y_test

dtr = DecisionTreeRegressor()
dtr.fit(  X_train, y_train  )
dtr.score(  X_test, y_test  )

-0.040185477637938005

### RandomForest

![RandomForest](https://github.com/gzone1357/Image1/raw/main/rf.png)

In [ ]:
# RandomForest 머신러닝 모델링

from sklearn.ensemble import RandomForestRegressor

In [ ]:
# ? , shift+Tab 활용하여 도움말 보기

RandomForestRegressor

sklearn.ensemble._forest.RandomForestRegressor

### RandomForestRegressor 모델 생성시 트리의 갯수 50, 트리의 깊이 6 <font color='blue'>하이퍼 파라미터</font> 넣어보자!!

In [ ]:
# 1. RandomForestRegressor 모델 정의 : 트리의 갯수 50, 트리의 깊이 6 -> rfr 저장
# 2. rfr 모델 학습 : X_train, y_train
# 3. rfr 모델 성능확인 : X_test, y_test

rfr = RandomForestRegressor( n_estimators=50, max_depth=6 )
rfr.fit(  X_train, y_train  )
rfr.score(  X_test, y_test  )

0.304091723316946

In [ ]:
# 만든 RandomForest 모델의 성능이 잘 나오는지 확인하기 전에 테스트셋의 첫번째 데이터와 정답 확인

X_test[0], y_test[0]

(array([19.82,  1.  ,  0.  ,  1.  ,  1.  ,  2.  ]), 3.18)

In [ ]:
# 테스트셋의 0 라인 샘플 데이터을 모델 입력해서 예측하기
# rfr 모델의 predict 함수 활용
# 입력 : [X_test[0]], 결과 : pred 저장
# pred 결과 출력

pred = rfr.predict([X_test[0]])
print(pred)

[2.94882608]

<br>
<br>
<br>

---

## **5. [분류모델 ] X, y 나누기**
- 지도학습 경우 데이터와 정답이 있어야 합니다.
- 데이터에 해당하는 X와 정답에 해당하는 y가 있어야 합니다.
- 아래와 같이 판다스를 이용하면 X, y를 쉽게 나눌수 있어요.
- X, y 데이터를 가지고 모델 학습하고 검증할수 있는 학습 데이터셋과 테스트 데이터셋으로 나눠 사용합니다.
- 그리고 레이블(y) 값을 보고 회귀 모델인지, 분류 모델인지 구별할수 있어요.
  - 레이블(y) : 학점 A/B/C/DF , 남녀 남/여, 숫자 0~9 --> 범주형으로 되어 있으면 분류 모델
  - 레이블(y) : 삼성전자 주가, 습도/온도, 유가동향등 --> 연속형으로 되어 있으면 회귀 모델

### **<font color=blue>우리는 분류 모델을 해야 되는데, 어떤 컬럼을 정답(레이블, y)를 정할까요?</font>**
### **<font color=blue>분류모델 위해서 범주형 컬럼을 레이블(y)로 선택해야 합니다.</font>**

In [ ]:
# tips2 데이터프레임의 뒤 5개 행 라인 보기
# 범주형 값들이 있는 컬럼은 무엇이 있나요?

tips2.tail()

     total_bill   tip  sex  smoker  day  time  size
239       29.03  5.92    1       0    1     1     3
240       27.18  2.00    0       1    1     1     2
241       22.67  2.00    1       1    1     1     2
242       17.82  1.75    1       0    1     1     2
243       18.78  3.00    0       0    3     1     2

### **<font color=blue>범주형 값을 나타내는 컬럼이 sex, smoker, day, time, size 컬럼들이 있네요</font>**

In [ ]:
# 다시 한번 tips2 내용을 보겠습니다.

tips2.head(3)

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     1     2
1       10.34  1.66    1       0    2     1     3
2       21.01  3.50    1       0    2     1     3

### **그중에서 정답(레이블, y)을 smoker 컬럼으로 정했고, smoker의 값들이 범주형 값이니 <font color=blue>분류 모델</font>이 되겠네요.**

In [ ]:
# tips2 테이블에서 smoker 컬럼만 제외하면 나머지가 X가 되겠네요.
# smoker 컬럼만 제외한 나머지 컬럼 ['total_bill', 'tip', 'sex', 'day', 'time', 'size'] 조회해 봅시다.

tips2[ ['total_bill', 'tip', 'sex', 'day', 'time', 'size'] ]

     total_bill   tip  sex  day  time  size
0         16.99  1.01    0    2     1     2
1         10.34  1.66    1    2     1     3
2         21.01  3.50    1    2     1     3
3         23.68  3.31    1    2     1     2
4         24.59  3.61    0    2     1     4
..          ...   ...  ...  ...   ...   ...
239       29.03  5.92    1    1     1     3
240       27.18  2.00    0    1     1     2
241       22.67  2.00    1    1     1     2
242       17.82  1.75    1    1     1     2
243       18.78  3.00    0    3     1     2

[244 rows x 6 columns]

In [ ]:
# 레이블(y)는 tips2 테이블에서 smoker 컬럼만 가져오면 되겠네요.

tips2['smoker']

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    1
241    1
242    0
243    0
Name: smoker, Length: 244, dtype: int64

### **<font color=blue>판다스의 drop 함수를 이용하면 쉽게 X, y를 나눌수 있어요!!</font>**

In [ ]:
# ? 활용하여 도움말 보기

tips2.drop?

In [ ]:
# Tab 키를 이용해서 자동 완성 황용하기

tips2.dro

In [ ]:
# X 데이터 분리 : 판다스 drop 함수 활용
# 입력 : 'smoker', axis=1

X = tips2.drop('smoker', axis=1)

In [ ]:
# 분리된 X 데이터 확인 : 출력결과가  데이터프레임 확인할수 있음.
# 레이블 smoker 컬럼은 보이지 않음을 확인할수 있습니다.

X

     total_bill   tip  sex  day  time  size
0         16.99  1.01    0    2     1     2
1         10.34  1.66    1    2     1     3
2         21.01  3.50    1    2     1     3
3         23.68  3.31    1    2     1     2
4         24.59  3.61    0    2     1     4
..          ...   ...  ...  ...   ...   ...
239       29.03  5.92    1    1     1     3
240       27.18  2.00    0    1     1     2
241       22.67  2.00    1    1     1     2
242       17.82  1.75    1    1     1     2
243       18.78  3.00    0    3     1     2

[244 rows x 6 columns]

In [ ]:
# y 데이터 분리 : 'smoker' 컬럼값만 분리

y = tips2['smoker']

In [ ]:
# 분리된 y 데이터 확인 : 데이터 타입이 Series 확인
# y 값이 정수 0과1의 범주형으로 되어 있음 확인

y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    1
241    1
242    0
243    0
Name: smoker, Length: 244, dtype: int64

### **X, y 데이터를 가지고 학습 데이터셋과 테스트 데이터셋 만들어 볼게요.**

In [ ]:
# X, y 데이터를 가지고 학습 데이터셋과 테스트 데이터셋 만들어 주는 train_test_split 함수가 있습니다.
# train_test_split 함수를 이용하면 쉽게 학습 데이터셋과 테스트 데이터셋 만들수 있습니다.
# 사이킷런의 train_test_split 함수 불러 옵니다.

from sklearn.model_selection import train_test_split

In [ ]:
# ? 활용하여 도움말 보기
train_test_split?

In [ ]:
# train_test_split 함수
# 1. X ,y 입력
# 2. test_size=0.2 --> train set : test set  = 8 : 2
# 3. random_state 사용하지 않으면 실행할때마다 학습셋과 테스트셋이 다르게 나와 고정하기 위해 사용
# 4. train_test_split 함수 결과로 X_train, X_test, y_train, y_test 나옴.

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42 )

In [ ]:
# 학습 데이터셋과 테스트 데이터셋의 사이즈 확인

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((195, 6), (49, 6), (195,), (49,))

In [ ]:
# 뒤쪽에서 사용하게 편하게 데이터프레임을 넘파이(numpy)로 변경합니다.

X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values

<br>
<br>
<br>

---

## **6. (분류) 머신러닝 모델링**
- DecisionTree 결정트리
- RandomForest 앙상블

### DecisionTree

![결정트리](https://github.com/gzone1357/Image1/raw/main/tree-depth-2.png)

In [ ]:
# 외우면 좋지만, 다 외울수 없기에
# Tab 키를 활용해서 자동완성 사용하자.
# 그리고 레이블(y)값을 smoker로 정햇으니, 범주형 값들이므로 분류 모델입니다.
# 회귀 모델을 선택해야 합니다.

from sklearn.tree import De

In [ ]:
# DecisionTree 머신러닝 모델링
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# ? , shift+Tab 활용하여 도움말 보기
DecisionTreeClassifier?

In [ ]:
# 1. DecisionTreeClassifier 모델 정의 -> dtc 저장
# 2. dtc 모델 학습 : X_train, y_train
# 3. dtc 모델 성능확인 : X_test, y_test

dtc = DecisionTreeClassifier()
dtc.fit( X_train, y_train )
dtc.score( X_test, y_test )

0.6938775510204082

### RandomForest

![RandomForest](https://github.com/gzone1357/Image1/raw/main/rf.png)

In [ ]:
# RandomForest 머신러닝 모델링
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# ? , shift+Tab 활용하여 도움말 보기
RandomForestClassifier

sklearn.ensemble._forest.RandomForestClassifier

In [ ]:
# 1. RandomForestClassifier 모델 정의 -> rfc 저장
# 2. rfc 모델 학습 : X_train, y_train
# 3. rfc 모델 성능확인 : X_test, y_test

rfc = RandomForestClassifier()
rfc.fit( X_train, y_train )
rfc.score( X_test, y_test )

0.6530612244897959

In [ ]:
# 테스테셋의 0 라인 샘플 데이터와 정답 확인

X_test[0], y_test[0]

(array([19.82,  3.18,  1.  ,  1.  ,  1.  ,  2.  ]), 0)

In [ ]:
# 테스테셋의 0 라인 샘플 데이터을 모델 입력해서 예측하기
# rfc 모델의 predict 함수 활용
# 입력 : [X[0]], 결과 : pred 저장
# pred 결과 출력

pred = rfc.predict([X_test[0]])
print(pred)

[0]

<br>
<br>
<br>

# **[실습] 머신러닝 모델링하기**

**아래 가이드에 따라 tips 데이터프레임을 활용하여 머신러닝 모델을 만드세요.**

- **회귀 모델 만들기**
  - 대상 데이터 : tips 데이터프레임
  - X, y 데이터 만들기
    - y 레이블 : total_bill
    - x 퓨쳐 : total_bill 제외한 나머지
  - train_test_split 함수를 활용해서 학습 데이터셋과 테스트 데이터셋을 만드세요.
    - 학습데이터셋 : 테스트데이터셋 = 8 : 2
    - random_state : 41  
  - KNN 모델을 만들고 학습하세요.
  - 만든 KNN 모델을 활용해서 아래 시뮬레이션 데이터에 대한 예측하세요.
    - 시뮬레이션 데이터 :  [3.23, 1.  , 0.  , 2.  , 1.  , 2.  ]

- **분류 모델 만들기**
  - 대상 데이터 : tips 데이터프레임
  - X, y 데이터 만들기
    - y 레이블 : day
    - x 퓨쳐 : day 제외한 나머지
  - train_test_split 함수를 활용해서 학습 데이터셋과 테스트 데이터셋을 만드세요.
    - 학습데이터셋 : 테스트데이터셋 = 8 : 2
    - random_state : 41  
  - KNN 모델을 만들고 학습하세요.
  - 만든 KNN 모델을 활용해서 아래 시뮬레이션 데이터에 대한 예측하세요.
    - 시뮬레이션 데이터 :  [14.78,  3.23,  1.  ,  0.  ,  1.  ,  2.  ]

**회귀 KNN 머신러닝 모델**

In [ ]:
# X, y 나누기
X = tips.drop('total_bill', axis=1)
y = tips[ 'total_bill' ]

In [ ]:
# 학습 데이터셋과 테스트 데이터셋 나누기
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=41 )
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((195, 6), (49, 6), (195,), (49,))

In [ ]:
# KNeighborsRegressor 모델 학습
# n_neighbors 이웃갯수 : 3

from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [ ]:
# KNN 모델을 활용해서 시뮬레이션 데이터 예측하기

simul = [3.23, 1. , 0. , 2. , 1. , 2. ]
knn.predict([ simul ])

array([20.00333333])

<br>

**분류 KNN 머신러닝 모델**

In [ ]:
# X, y 나누기
X = tips.drop('day', axis=1)
y = tips[ 'day' ]

In [ ]:
# 학습 데이터셋과 테스트 데이터셋 나누기
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=41 )
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((195, 6), (49, 6), (195,), (49,))

In [ ]:
# KNeighborsClassifier 모델 학습
# n_neighbors 이웃갯수 : 3

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
# KNN 모델을 활용해서 시뮬레이션 데이터 예측하기

simul = [14.78,  3.23,  1.  ,  0.  ,  1.  ,  2.  ]
knn.predict([ simul ])

array([1])

---